#!/bin/bash
for confluence in `cat confluences.secret`
do
  DA_DS=confluence DA_CONFLUENCE_MULTI_ORIGIN=1 DA_CONFLUENCE_ENRICH=1 DA_CONFLUENCE_ES_URL="${ES_URL}" DA_CONFLUENCE_RAW_INDEX=dads-confluence-raw DA_CONFLUENCE_RICH_INDEX=dads-confluence DA_CONFLUENCE_DEBUG=1 DA_CONFLUENCE_DB_PORT=13306 DA_CONFLUENCE_DB_NAME=sortinghat DA_CONFLUENCE_DB_USER=sortinghat DA_CONFLUENCE_DB_PASS=pwd DA_CONFLUENCE_NO_SSL_VERIFY='' DA_CONFLUENCE_MAX_CONTENTS=500 DA_CONFLUENCE_ES_BULK_SIZE=500 DA_CONFLUENCE_URL="$confluence" ./dads
done

