package mocks

import (
	"github.com/LF-Engineering/da-ds/affiliation"
	mock "github.com/stretchr/testify/mock"
)

// IdentityProvider is an autogenerated mock type for the ESClientProvider type
type  IdentityProvider struct {
	mock.Mock
}


// GetIdentity
func (_i *IdentityProvider) GetIdentity(key string, val string) (*affiliation.Identity, error) {

}

