// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	affiliation "github.com/LF-Engineering/da-ds/affiliation"

	mock "github.com/stretchr/testify/mock"
)

// IdentityProvider is an autogenerated mock type for the IdentityProvider type
type IdentityProvider struct {
	mock.Mock
}

// GetIdentity provides a mock function with given fields: key, val
func (_m *IdentityProvider) GetIdentity(key string, val string) (*affiliation.Identity, error) {
	ret := _m.Called(key, val)

	var r0 *affiliation.Identity
	if rf, ok := ret.Get(0).(func(string, string) *affiliation.Identity); ok {
		r0 = rf(key, val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*affiliation.Identity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(key, val)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
