// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Auth0ClientProvider is an autogenerated mock type for the Auth0ClientProvider type
type Auth0ClientProvider struct {
	mock.Mock
}

// GetToken provides a mock function with given fields:
func (_m *Auth0ClientProvider) GetToken() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
