package pipermail

import (
	"os"
	"strings"
	"time"
)

const (
	// ModMboxThreadStr ...
	ModMboxThreadStr = "/thread"
	// Pipermail datasource
	Pipermail = "pipermail"
	// PiperBackendVersion ...
	PiperBackendVersion = "0.0.1"
	// MessageDateField ...
	MessageDateField = "date"
	// Message ...
	Message = "message"
	// MessageIDField ...
	MessageIDField = "Message-ID"
	// Unknown ...
	Unknown = "Unknown"
)

var (
	// CompressedTypes ...
	CompressedTypes = []string{".gz", ".bz2", ".zip", ".tar", ".tar.gz", ".tar.bz2", ".tgz", ".tbz"}
	// AcceptedTypes ...
	AcceptedTypes = []string{".mbox", ".txt"}
	// CombinedTypes ...
	CombinedTypes []string
	// MONTHS ...
	MONTHS = map[string]int{"January": 1, "February": 2, "March": 3, "April": 4, "May": 5, "June": 6, "July": 7, "August": 8, "September": 9, "October": 10, "November": 11, "December": 12}
	// DefaultDateTime ...
	DefaultDateTime = time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)
	// MessageSeparator ...
	MessageSeparator = []byte("\nFrom")
	// PiperRawMapping ...
	PiperRawMapping = []byte(`{"mappings":{"dynamic":true,"properties":{"metadata__updated_on":{"type":"date"},"data":{"properties":{"body":{"dynamic":false,"properties":{}}}}}}}`)
	// PiperRichMapping ...
	PiperRichMapping = []byte(`{"mappings":{"dynamic_templates":[{"notanalyzed":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}},{"int_to_float":{"match":"*","match_mapping_type":"long","mapping":{"type":"float"}}},{"formatdate":{"match":"*","match_mapping_type":"date","mapping":{"format":"strict_date_optional_time||epoch_millis","type":"date"}}}]}}`)
	// EmailObfuscationPatterns ...
	EmailObfuscationPatterns = []string{" at ", "_at_", " en "}
	// ArchiveDownloadsPath ...
	ArchiveDownloadsPath = strings.TrimSpace(os.Getenv("HOME") + "/.perceval/mailinglists/")
)
