package pipermail

import "time"

const (
	// ModMboxThreadStr ...
	ModMboxThreadStr = "/thread"
	// Pipermail datasource
	Pipermail = "pipermail"
	// PiperBackendVersion ...
	PiperBackendVersion = "0.0.1"
	// ArchiveDownloadsPath ...
	ArchiveDownloadsPath = "/Users/code/.dads/mailinglists/"
	// MessageDateField ...
	MessageDateField = "date"
	// Message ...
	Message = "message"
	// MessageIDField ...
	MessageIDField = "Message-ID"
)

var (
	// CompressedTypes ...
	CompressedTypes = []string{".gz", ".bz2", ".zip", ".tar", ".tar.gz", ".tar.bz2", ".tgz", ".tbz"}
	// AcceptedTypes ...
	AcceptedTypes = []string{".mbox", ".txt"}
	// CombinedTypes ...
	CombinedTypes []string
	// MONTHS ...
	MONTHS = map[string]int{"January": 1, "February": 2, "March": 3, "April": 4, "May": 5, "June": 6, "July": 7, "August": 8, "September": 9, "October": 10, "November": 11, "December": 12}
	// DefaultDateTime ...
	DefaultDateTime = time.Date(1970, 1, 1, 0, 0, 0, 0, time.UTC)
	// MessageSeparator ...
	MessageSeparator = []byte("\nFrom")
	// PiperRawMapping ...
	PiperRawMapping = []byte(`{"mappings":{"dynamic":true,"properties":{"metadata__updated_on":{"type":"date"},"data":{"properties":{"body":{"dynamic":false,"properties":{}}}}}}}`)
	// PiperRichMapping ...
	PiperRichMapping = []byte(`{"mappings":{"properties":{"metadata__updated_on":{"type":"date"},"Subject_analyzed":{"type":"text","fielddata":true,"index":true},"body":{"type":"text","index":true}}}}`)
	// EmailObfuscationPatterns ...
	EmailObfuscationPatterns = []string{" at ", "_at_", " en "}
)
